import { FiArrowUpRight, FiCheck, FiCompass, FiHeart, FiLayers, FiRadio, FiUsers, FiWind } from 'react-icons/fi'
import { Link } from 'react-router-dom'

export default function About() {
  return (
    <div className="page-shell">
      <div className="page-heading reveal"><div><p className="eyebrow">The idea behind Noura</p><h1>Less noise.<br />More signal.</h1></div><p className="content-copy">We believe the internet can feel human again: curious, generous, and designed around attention instead of urgency.</p></div>
      <div className="feature-grid stagger-grid"><article className="surface feature-card"><span className="feature-icon"><FiWind /></span><h3>Quiet by design</h3><p>No endless feeds or frantic prompts. Just enough structure to help you stay present.</p></article><article className="surface feature-card"><span className="feature-icon"><FiRadio /></span><h3>Curious by nature</h3><p>Every collection is a starting point for a better question, not a final answer.</p></article><article className="surface feature-card"><span className="feature-icon"><FiHeart /></span><h3>Made with care</h3><p>Small details matter when a product becomes part of your everyday ritual.</p></article></div>
      <section className="about-stats surface reveal"><div><strong>240+</strong><span>things worth discovering</span></div><div><strong>18k</strong><span>curious people around us</span></div><div><strong>4.9</strong><span>average community rating</span></div><div><strong>24/7</strong><span>room for a new idea</span></div></section>
      <section className="about-story reveal-side"><div><p className="eyebrow">How we work</p><h2>A slower process makes better products.</h2><p>We collect the useful, remove the noise, and leave enough space for you to decide what belongs in your day.</p></div><div className="about-timeline"><article><span>01</span><div><h3>Notice</h3><p>We start with a small question and pay attention to the details.</p></div></article><article><span>02</span><div><h3>Shape</h3><p>We turn good discoveries into clear, useful experiences.</p></div></article><article><span>03</span><div><h3>Share</h3><p>We put them in your hands and let your curiosity take over.</p></div></article></div></section>
      <section className="about-principles"><div className="section-heading"><div><p className="eyebrow">Our principles</p><h2>What stays true.</h2></div><FiCompass className="section-symbol" /></div><div className="principle-grid stagger-grid"><article className="surface principle-card"><FiLayers /><h3>Useful over noisy</h3><p>Every detail should earn its place and help you move forward.</p><span><FiCheck /> Thoughtful by default</span></article><article className="surface principle-card"><FiUsers /><h3>People over metrics</h3><p>We design for real attention, real lives, and real moments.</p><span><FiCheck /> Human at the center</span></article><article className="surface principle-card"><FiHeart /><h3>Care in the small things</h3><p>Good experiences are built from hundreds of considerate decisions.</p><span><FiCheck /> Made to last</span></article></div></section>
      <section className="about-cta surface reveal"><div><p className="eyebrow">Keep exploring</p><h2>There is always another good idea nearby.</h2></div><div><p>Start with the collection or tell us what you are looking for.</p><div className="hero-actions"><Link className="primary-action" to="/products">Explore products <FiArrowUpRight /></Link><Link className="secondary-action" to="/contact">Talk to us</Link></div></div></section>
    </div>
  )
}
